language: c

env:
  - global:
    - WARNINGS_ARE_ERRORS=0

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
  - sudo apt-get install python-numpy python-scipy python-matplotlib ipython ipython-notebook python-pandas python-sympy python-nose
install:
  - ./travis-tool.sh github_package hadley/testthat
  - ./travis-tool.sh github_package hadley/assertthat
  - ./travis-tool.sh github_package berndbischl/BBmisc
  - ./travis-tool.sh github_package berndbischl/parallelMap
  - ./travis-tool.sh github_package berndbischl/ParamHelpers
  - ./travis-tool.sh github_package jimhester/covr
  - ./travis-tool.sh r_install soobench
  - ./travis-tool.sh install_deps
script: ./travis-tool.sh run_tests

after_success:
  - Rscript -e 'library(covr);coveralls()'

after_failure:
  - ./travis-tool.sh dump_logs

notifications:
  email:
    recipients:
      - j.bossek@gmail.com
    on_success: change
    on_failure: always
